modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "msd"
version = "${mod_version}"
displayName = "MTR Station Decoration Addon"
authors = "AIDA64S, Santorsia, Zbx1425"
description = "A Station Decoration Addon for the Minecraft Transit Railway Mod"
logoFile = "icon.png"

[[dependencies.msd]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_min_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.msd]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.msd]]
modId = "mtr"
type = "required"
versionRange = "[${mtr_version},)"
ordering = "AFTER"
side = "BOTH"
